### ISSUE TITLE
lxcfs rarely crashes in pivot_root

### ISSUE THREAD

**Issue by ralt** [lxc/lxcfs#291]
Very rarely, but often enough on our fleet, lxcfs crashes with a segfault.

I haven't been able to compile it with debugging symbols, so that's the information I've got from the coredump:

```
(gdb) bt
#0  0x00007f2484ffefff in killpg () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f247fffebc0 in ?? ()
#2  0xfffffffe7fffffff in ?? ()
#3  0xffffffffffffffff in ?? ()
#4  0xffffffffffffffff in ?? ()
#5  0xffffffffffffffff in ?? ()
#6  0xffffffffffffffff in ?? ()
#7  0xffffffffffffffff in ?? ()
#8  0xffffffffffffffff in ?? ()
#9  0xffffffffffffffff in ?? ()
#10 0xffffffffffffffff in ?? ()
#11 0xffffffffffffffff in ?? ()
#12 0xffffffffffffffff in ?? ()
#13 0xffffffffffffffff in ?? ()
#14 0xffffffffffffffff in ?? ()
#15 0xffffffffffffffff in ?? ()
#16 0xffffffffffffffff in ?? ()
#17 0xffffffffffffffff in ?? ()
#18 0x000000000005f02a in ?? ()
#19 0x00007f248500042a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#20 0x00007f2485794ff9 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#21 0x00007f24857964b9 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#22 0x00007f2485796767 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#23 0x00007f24857a25a1 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#24 0x00007f248579edd8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#25 0x00007f24853724a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#26 0x00007f24850b4d0f in epoll_pwait () from /lib/x86_64-linux-gnu/libc.so.6
#27 0x0000000000000000 in ?? ()
(gdb) 
```

The interesting part is this, though:

```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f247ffff700 (LWP 29601) 0x00007f2484ffefff in killpg () from /lib/x86_64-linux-gnu/libc.so.6
  2    Thread 0x7f247cff9700 (LWP 29351) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  3    Thread 0x7f247e7fc700 (LWP 25140) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  4    Thread 0x7f245effd700 (LWP 29540) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  5    Thread 0x7f247effd700 (LWP 25181) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  6    Thread 0x7f247d7fa700 (LWP 29613) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  7    Thread 0x7f247dffb700 (LWP 29650) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  8    Thread 0x7f2484db2700 (LWP 29585) 0x00007f24850b5303 in pivot_root () from /lib/x86_64-linux-gnu/libc.so.6
  9    Thread 0x7f245f7fe700 (LWP 25174) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  10   Thread 0x7f245e7fc700 (LWP 24980) 0x00007f248537b22d in read () from /lib/x86_64-linux-gnu/libpthread.so.0
  11   Thread 0x7f2485be3b40 (LWP 836) 0x00007f248537a556 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) 
```

Which tells me that it looks like a race condition triggered when one thread is in `pivot_root`.

Any pointer on how I could debug this more easily?

**Comment by stgraber** [comment]
What version of lxcfs is this?

It could be that adding the symbols packages for libfuse and lxcfs would help track this down a bit.
